--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sully_vian/.wallpapers/plants.jpg"

-- Special
background="#040F0A"
foreground="#bbc4af"
cursor="#bbc4af"

-- Colors
color0="#040F0A"
color1="#1D5742"
color2="#275743"
color3="#346C4E"
color4="#536C4F"
color5="#3D8555"
color6="#608B65"
color7="#bbc4af"
color8="#82897a"
color9="#1D5742"
color10="#275743"
color11="#346C4E"
color12="#536C4F"
color13="#3D8555"
color14="#608B65"
color15="#bbc4af"
