# Shell variables
# Generated by 'wal'
wallpaper='/home/sully_vian/.wallpapers/plants.jpg'

# Special
background='#040F0A'
foreground='#bbc4af'
cursor='#bbc4af'

# Colors
color0='#040F0A'
color1='#1D5742'
color2='#275743'
color3='#346C4E'
color4='#536C4F'
color5='#3D8555'
color6='#608B65'
color7='#bbc4af'
color8='#82897a'
color9='#1D5742'
color10='#275743'
color11='#346C4E'
color12='#536C4F'
color13='#3D8555'
color14='#608B65'
color15='#bbc4af'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
